f2l = [
    "R' FRF' RU' R' URU' R' U2RU' R')",
    "y (U' L' ULU) y' (RU' R')",
    " (URU' R' U') y (L' UL)",
    "y (L' U' LUL' U' L)",
    "RU' R' URU' R'",
    "y (L' U' LU2) (L' ULU' L' U' L)",
    " y (L' U' LUL' ULU2) y' (RUR')",
    "RUR' U' RUR'",
    " y (L' ULU' L' UL)",
    "(RUR' U2) (RU' R' URUR')",
    "(RUR' U') (RU' R' U2) y (L' U' L)",
    " (RUR' U') (RUR' U') (RUR')",
    " (RU' R' U) y (L' UL)",
    "RU2R' U' RUR'",
    "y (L' U' LU2) (L' U' LU) (L' U' L)",
    " y (L' U2LUL' U' L)",
    "RUR' U2RUR' U' RUR'",
    "RU' R' U2 RUR'",
    "y (U' L' U2 LU' L' U L)",
    " y (L' ULU2L' U' L)",
    " URU2R' URU' R'",
    " y (UL' ULU2L' UL)",
    "y (UL' U' LU') y' (RUR')",
    " U' RU' R' URUR'",
    " (RU' R' U2) y (L' U' L)",
    " y (U' L' UL)",
    "RU' R' URU' R' U2RU' R'",
    " RUR'",
    " y (UL' U2LU2L' UL)",
    " y (UL' U' LU2L' UL)",
    " U' RUR' URUR'",
    "U' RU' R' U2RU' R'",
    " (U' RUR' U) y ( L' U' L)",
    "URU' R'",
    " y (L' ULU' L' ULU2L' UL)",
    "y (UL' ULU' L' U' L)",
    "y (L' ULU2) y' (RUR')",
    "U' RUR' U2RU' R'",
    " y (UL' U' LU' L' U' L)",
    " U' RU2R' U2RU' R'",
    " y (L' U' L)",
]